### PR TITLE
15.0 mig mass mailing delivery

### PR DESCRIPTION
**Pull request by nikunjantala**

### CODE REVIEW

**Comment by alihashaam** [comment]
@nikunjantala 

is this PR in WIP or ready for review?

**Comment by jans23** [comment]
It's ready for review.

**Comment by alihashaam** [comment]
@nikunjantala @jans23 
Review is done and PR is ready to merge. The only point is that 'sale_order_count' is not displayed in views, is it intentional?

**Comment by jans23** [comment]
@alihashaam Not sure what you mean. Please share a screenshot.

**Comment by nikunjantala** [comment]
@jans23 Mean sale_order_count field is not added in any view. We actually not needed in view. We just use that field in advance filter.
Selection_999(428)

**Comment by jans23** [comment]
Yes, we only need this field in filters.

**Pull request merged**
