### PR TITLE
15.0 mig sale payment

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by jans23** [comment]
@dsolanki-initos You see the conflicts to be fixed?

**Review by ikapasi-initos — APPROVED** [review]
Code review and functional tests.
LGTM.

**Comment by manengel** [comment]
@dsolanki-initos @jans23 @ikapasi-initos 
I have a question in general before starting the actual review: Is this the way it is supposed to be that this PR is open at the same 
time as https://github.com/OCA/sale-workflow/pull/2019? While it does make sense to both get internal and external feedback, this right now also means the code must be currently maintained twice.

**Comment by jans23** [comment]
Right. I'm closing this in favor of [2019](https://github.com/OCA/sale-workflow/pull/2019). OCA's review should be sufficient so need for @manengel to review it.

**Pull request closed without merging**
