### PR TITLE
[MIG] website_menu_url_translate: Migration to 15.0

### PR DESCRIPTION
**Pull request by nikunjantala**

### CODE REVIEW

**Comment by jans23** [comment]
Please submit a PR to OCA.

**Review by dsolanki-initos — COMMENTED** [review]
Can you please remove unnecessary commented code and tried to understand the functionality but can not traced exact functionality of this module

**Comment by jans23** [comment]
Any update?

**Comment by jans23** [comment]
@nikunjantala See comments above.

**Comment by nileshsheliya** [comment]
Can you please let me know which OCA repository we need to push this module?

**Comment by jans23** [comment]
https://github.com/OCA/website/

**Comment by nileshsheliya** [comment]
Can you create its fork please.

**Comment by jans23** [comment]
I just invited you to the fork.

**Comment by nileshsheliya** [comment]
Created PR : https://github.com/OCA/website/pull/912

**Pull request closed without merging**
