### PR TITLE
[15.0][MIG] stock tracking validation

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by alihashaam** [comment]
@jans23 @dsolanki-initos 

I am starting the review here: Somehow I am not able to change the reviewer from Manuel to me on the MR, hence the comment

**Comment by alihashaam** [comment]
@dsolanki-initos 

There are few small warning, if you do isort and pylint check locally. Can you please fix them?

**Comment by dsolanki-initos** [comment]
> @dsolanki-initos
> 
> There are few small warning, if you do isort and pylint check locally. Can you please fix them?

Sure, I'll fix it.

**Comment by dsolanki-initos** [comment]
> @dsolanki-initos
> 
> There are few small warning, if you do isort and pylint check locally. Can you please fix them?

@alihashaam, I've fixed the warnings, Please check it.

**Comment by alihashaam** [comment]
@jans23 this MR is ready to be merged

**Pull request merged**
