### PR TITLE
[MIG] partner_user_status: Migration to 15.0

### PR DESCRIPTION
**Pull request by nikunjantala**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
Code Review and Functional Test, LGTM!

**Comment by jans23** [comment]
Shouldn't this review happen in a PR to OCA instead?

**Comment by dsolanki-initos** [comment]
> Shouldn't this review happen in a PR to OCA instead?

Yes but there is not PR created for OCA and did not specified for OCA submit in migration sheet

**Comment by jans23** [comment]
@nikunjantala Please create a PR from https://github.com/Nitrokey/odoo-partner-contact/ to https://github.com/OCA/partner-contact/

**Comment by nileshsheliya** [comment]
Ok

**Comment by nileshsheliya** [comment]
I created PR, please see it here : https://github.com/OCA/partner-contact/pull/1295

**Pull request closed without merging**
